services:
  - type: web
    name: cloud-desktop
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: VNC_PW
        value: admin123
      - key: PORT
        value: "8080"
    healthCheckPath: /
